#!/usr/bin/env bash
# build-compound-verifier.sh - emit a single verify-ultracook.sh that runs the
# per-action verifier set bound to ONE action (NOT the whole goal.yaml.target
# .verifiers - that's the workflow-level set, run only at verify_* phases).
#
# Usage: build-compound-verifier.sh --goal-dir <dir> --action <name> [--iter <N>]
#
# Reads:
#   - action-vocab.yaml          → action's verifier binding
#   - goal.yaml                  → placeholder values (test_cmd via profile)
#   - state.json                 → pr_number, plan_dir, etc.
#
# Writes: {goal-dir}/verify-ultracook-{action}.sh (executable)
# Stdout: absolute path to the written verify script.
# Exit: 0 if a verifier was bound + script written; 1 if no verifier for this
#       action (caller should treat as "no verifier needed" - pass through);
#       2 on input error.

set -uo pipefail

GOAL_DIR=""; ACTION=""; ITER="000"
while [ $# -gt 0 ]; do
  case "$1" in
    --goal-dir) GOAL_DIR="${2:-}"; shift 2 ;;
    --action)   ACTION="${2:-}"; shift 2 ;;
    --iter)     ITER="${2:-000}"; shift 2 ;;
    *) echo "build-compound-verifier.sh: unknown arg: $1" >&2; exit 2 ;;
  esac
done
[ -z "$GOAL_DIR" ] && { echo "--goal-dir required" >&2; exit 2; }
[ -z "$ACTION" ]   && { echo "--action required"   >&2; exit 2; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VOCAB="$(dirname "$SCRIPT_DIR")/references/action-vocab.yaml"
PYBIN="${HOME}/.claude/skills/.venv/bin/python3"; [ -x "$PYBIN" ] || PYBIN="$(command -v python3)"

# Resolve per-action verifier from the vocab (single dict, not a list).
VERIFIER_JSON="$(GOAL_DIR="$GOAL_DIR" ACTION="$ACTION" VOCAB="$VOCAB" "$PYBIN" - <<'PY'
import os, json, yaml, tomllib, subprocess
vocab = yaml.safe_load(open(os.environ["VOCAB"]))
a = vocab.get("actions", {}).get(os.environ["ACTION"]) or {}
v = a.get("verifier")
if not v:
    print(json.dumps({}))
    raise SystemExit(0)
# Interpolate placeholders from goal + state + profile
goal_dir = os.environ["GOAL_DIR"]
goal  = yaml.safe_load(open(os.path.join(goal_dir, "goal.yaml")))
state = json.load(open(os.path.join(goal_dir, "state.json")))
remote = (goal.get("project") or {}).get("remote_url", "")
script_dir = os.path.dirname(os.path.dirname(os.environ["VOCAB"])) + "/scripts"
look = subprocess.run([os.path.join(script_dir, "lookup-profile.sh"), "--remote-url", remote],
                      capture_output=True, text=True)
prof_path = look.stdout.strip() if look.returncode == 0 else None
prof = tomllib.load(open(prof_path, "rb")) if prof_path else {}
ph = {
    "pr_number":  str(state.get("pr_number","")),
    "plan_dir":   goal.get("plan_dir",""),
    "profile.test_cmd": (prof.get("verify") or {}).get("test_cmd",""),
}
def interp(s):
    if not isinstance(s, str): return s
    for k, val in ph.items():
        s = s.replace("{" + k + "}", str(val))
    return s
args = v.get("args") or {}
v_out = {"type": v.get("type",""), "args": {k: interp(val) for k, val in args.items()}}
print(json.dumps(v_out))
PY
)"

# Empty verifier → no-op exit (caller treats as "no verifier needed").
if [ "$VERIFIER_JSON" = "{}" ]; then
  exit 1
fi

OUT="${GOAL_DIR}/verify-ultracook-${ACTION}.sh"
SCRIPT_DIR_ESC="$(printf '%s' "$SCRIPT_DIR" | sed -E 's,[/.],\\&,g')"

# Generate the verify script. The single per-action verifier becomes a single
# eval-verifier.sh call. (If a future action needs MULTIPLE per-action
# verifiers, this is the place to expand; v0.1 binds one verifier per action.)
cat > "$OUT" <<EOF
#!/usr/bin/env bash
# Auto-generated by build-compound-verifier.sh for action='${ACTION}'.
# Exits 0 only when the bound per-action verifier passes. Used by Phase 5's
# auto-loop delegation as the single --verify command.

set -uo pipefail

GOAL_DIR="${GOAL_DIR}"
ACTION="${ACTION}"
ITER="${ITER}"
EVAL="${SCRIPT_DIR}/eval-verifier.sh"

# Per-verifier log for crash debuggability.
LOG="\${GOAL_DIR}/iterations/\${ITER}-\${ACTION}-verifier.log"
mkdir -p "\${GOAL_DIR}/iterations"

VERIFIER='${VERIFIER_JSON}'
TYPE="\$(printf '%s' "\$VERIFIER" | "${PYBIN}" -c 'import json,sys; print(json.load(sys.stdin)["type"])')"

# Translate JSON args → eval-verifier.sh flags.
mapfile -t FLAGS < <(printf '%s' "\$VERIFIER" | "${PYBIN}" -c '
import json, sys
v = json.load(sys.stdin)
for k, val in (v.get("args") or {}).items():
    print(f"--{k.replace(\"_\",\"-\")}")
    print(str(val))
')

result="\$("\$EVAL" --type "\$TYPE" "\${FLAGS[@]}" 2>>"\$LOG")"
echo "\$result" >> "\$LOG"
pass="\$(printf '%s' "\$result" | "${PYBIN}" -c 'import json,sys; d=json.load(sys.stdin); print("yes" if d.get("pass") is True else "no")')"
if [ "\$pass" = "yes" ]; then
  exit 0
else
  exit 1
fi
EOF

chmod +x "$OUT"
echo "$OUT"
